version: "3.9"

services:
  api:
    build: .
    container_name: taskflow_api
    restart: always
    environment:
      DATABASE_URL: postgresql://neondb_owner:I40ihKpRXrng@ep-damp-frost-a20kvwbz-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      SECRET_KEY: 1d766e21352385d5b32655eeaceab63a6b5b781ea788033f99c85fcc4199aca5
    ports:
      - "8000:8000"
    command: >
      sh -c "
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "