services:
  - type: web
    name: taskflow-api
    runtime: python
    repo: https://github.com/wubeabera123/taskflow-api
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3