"""add ai metadata to tasks

Revision ID: 2a418a03a237
Revises: ae764d41fc4a
Create Date: 2026-03-06 09:25:36.427908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a418a03a237'
down_revision: Union[str, Sequence[str], None] = 'ae764d41fc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_ai_generated')
    # ### end Alembic commands ###
