"""add ai_prompt to tasks

Revision ID: 37e867b69848
Revises: 2a418a03a237
Create Date: 2026-03-06 10:37:54.784516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e867b69848'
down_revision: Union[str, Sequence[str], None] = '2a418a03a237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('ai_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ai_prompt')
    # ### end Alembic commands ###
